### PR TITLE
Implement enter_do in terms of `yieldto()`

### PR DESCRIPTION
**Pull request by c42f**
For this specialized use case in enter_do we really only want the use of
an extra stack, but other than this, we probably don't need to involve
the main scheduler or have any other unrelated tasks be scheduled.

So it seems we can skip the main scheduler completely on the happy path.
When there's an error we do need the child task to run to completion so
that its error flag is set.

### CODE REVIEW

**Comment by c42f** [comment]
@tkf is this what you had in mind with `yieldto()`? The main oddity I found trying to do this was finding a way for the child task to run to completion so that its failure status can be set and we can access the exception stack of the failed task for full error reporting.

For proper task teardown, the child task needs to exit our user-defined code and end up running `jl_finish_task()` (which sets appropriate state flags and calls `Base.task_done_hook()` to handle task done notifications). The only way I could see to do this was to `schedule()` the child task in the case we're on an error path.

**Comment by tkf** [comment]
Yeah, this is approximately what I had in mind, including the `yieldto` in `catch`.

But I wasn't thinking "properly" finishing the task. Isn't the error handling of `func` already executed by the time the child task hit `yieldto(parent_task, :failed)`? For showing the error, isn't it enough to capture the error and backtrace in the catch block of the child task? Though maybe you wanted to use `TaskFailedException`?

**Comment by c42f** [comment]
> For showing the error, isn't it enough to capture the error and backtrace in the catch block of the child task? Though maybe you wanted to use TaskFailedException?

Yes I was trying to reuse the effort that went into making `TaskFailedException` print nicely.

But I guess it could arguably be neater to call `catch_stack()` within the child task and communicate that out to the parent. Just need a custom exception type, or use `CapturedException` if not preserving the whole exception stack.

**Comment by c42f** [comment]
I think it may be better to stick with the current implementation - it doesn't (potentially) loose the root cause in the exception stack, reuses an existing exception type, and the scheduler is only used on the exceptional code path.

That said, the `enter_do` implementation is really neat with `CapturedException` and `throwto`:

```julia
@! function enter_do(func::Function, args...; kws...)
    # We need a separate stack to run the do block, so we use a separate task
    # here for that purpose. We know exactly which order the parent and child
    # tasks should run in so we should be able to use explicit yields and not
    # involve the main scheduler.
    parent_task = current_task()
    child_task = @task try
        func(args...; kws...) do resources...
            yieldto(parent_task, resources)
        end
        # Success path: yield back to parent - `child_task` will never complete, but
        # we've already run whatever cleanup code in `func` so that should be ok.
        yieldto(parent_task, nothing)
    catch exc
        # Failure path
        Base.throwto(parent_task, CapturedException(exc, catch_backtrace()))
        # <-- unreachable - child is not rescheduled
    end
    res = yieldto(child_task)
    @defer begin
        # Allow child task to free any resources
        yieldto(child_task)
    end
    return res
end
```

**Comment by tkf** [comment]
> the `enter_do` implementation is really neat with `CapturedException` and `throwto`

Ooh, yes, this is nice. (But understandable to stick with the current one, to avoid relying on the internals.)

**Comment by c42f** [comment]
Ah, it was oh-so-tempting to use the more elegant implementation with `Base.throwto` but in the interests of reusing Base's existing error path for `wait()` I went with the current version.

**Comment by vtjnash** [comment]
Since those internal functions yieldto and especially throwto can sometimes be tricky to work with to avoid races and dropping errors, there is also Base._wait2 for pausing one Task for the completion of another, with or without error

**Comment by c42f** [comment]
Ah yes I saw `_wait2()` while looking around in there. I wasn't sure how to use it in this case though, so I went with a direct `schedule` and `wait()` because I wanted the error propagation that's built into `wait()`.

**Pull request merged**
