### PR TITLE
Fix use of yeildto() in enter_do()

### PR DESCRIPTION
**Pull request by c42f**
Under certain circumstances we'll not run the cleanup code in the
expected parent_task — if `detach_context_cleanup()` has been called,
it'll run in some async cleanup task fired from a finalizer.

This causes scheduling inconsistency as the original parent task may
have already run to completion, etc.

Generally this probably just shows how awful detach_context_cleanup()
actually is, and yet another demonstration of how it's hard to use
finalizers for this kind of thing :-(

### CODE REVIEW

**Comment by c42f** [comment]
@tkf this may interest you as an example of how things can go unexpectedly wrong when using `yieldto()` directly on deferred cleanup code.

**Comment by tkf** [comment]
Ah, interesting patch :)

Can this happen also when the context is shared across multiple tasks? Like the example in the OP of #7.

**Comment by c42f** [comment]
> Ah, interesting patch :)

It was hard to debug! Mostly tasks don't use the return value of `yieldto`, but Base uses it for communicating libuv error codes, so the way this manifested was as a bad type assertion in unrelated IO tasks which interleave with the cleanup code. I ended up instrumenting `ctx_switch` in the C code to figure out what was going on.

> Can this happen also when the context is shared across multiple tasks?

So considering the following kind of thing?

```julia
function f()
    @context begin
        parent = current_task()
        @sync begin
            child1 = @async @! enter_do(g)
            child2 = @async @! enter_do(g)
        end
    end
end
```

In that case we'd have `parent_task` equal to `child1` and `child2` in the two different `enter_do` blocks, but the cleanup code would be called by `parent`.  So yes, without this patch I think we have the same problem in that case.

**Comment by tkf** [comment]
> I ended up instrumenting `ctx_switch` in the C code to figure out what was going on.

That's Real Programming :grinning: 

> So considering the following kind of thing?

Yeah, exactly. I was thinking this is after all a tough but must-have fix when the context can cross tasks (even in single-threaded cases).

This (and your comment on hackability in REPL, back in JuliaCon) are nudging me towards thinking that `open(f, resource) do` type of resource management should really be "derived" from `open(resource) -> ctx`/`close(ctx)` API and not the other way around...

**Comment by c42f** [comment]
> That's Real Programming

Haha!  When I say "instrumenting" I mean "desparately hacking in some `printf` statements with the `from->to` task addresses :laughing:"

> This (and your comment on hackability in REPL, back in JuliaCon) are nudging me towards thinking that open(f, resource) do type of resource management should really be "derived" from open(resource) -> ctx/close(ctx) API and not the other way around...

I think the cleanup interface you've defined in `ContextManagers` is interesting because you can have actions which trigger on failure (`catch`) rather than just cleanup (`finally`). I'd been thinking that `ResourceContexts` needs that distinction as well — we're basically turning `try...catch...finally` into state machines and `@defer` by itself can't express the control flow into the `catch`

**Comment by tkf** [comment]
Yeah, I thought distinguishing success/fail/any exit could be important for covering "last 10%" use cases (somewhat influenced by the scope guard in D/C++). Though I probably should mention in the README of ContextManagers.jl that it was (almost) a direct rip-off of Python's context manager: https://docs.python.org/3/reference/datamodel.html#with-statement-context-managers. It's not really as ambitious as ResourceContexts.jl as I wasn't looking for a "novel" solution. I feel there could be some nice solution along with the line of ResourceContexts.jl and also the "Go 2" exception handling.

**Comment by c42f** [comment]
Heh, it seemed very pythonic, I guessed you took inspiration from python for some of it :-)

**Pull request merged**
